name: Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - main
      - feat/*

jobs:
  test:
    runs-on: gha-runner-scale-set
    permissions:
      contents: read

    steps:
      # Setup tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0
      - name: Setup Go environment
        uses: actions/setup-go@v6.2.0
        with:
          go-version: "1.24.4"
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Rollout environment and run tests
      - name: Start test environment
        run: |
          make test-env-start
      - name: Run integration tests
        run: |
          make test-integration
  cleanup:
    runs-on: gha-runner-scale-set
    needs: [test]
    if: ${{ always() }}
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0
      - name: Clean test environment
        run: |
          make test-env-stop
